### PR TITLE
Use release-plz for automatic release

### PR DESCRIPTION
**Pull request by NobodyXu**
release-plz would create new release-pr whenever new commits are merged, and once the release-pr is merged, it would create new release and tags, and publish it to crates.io

### CODE REVIEW

**Comment by NobodyXu** [comment]
IMG_4843

Cc @jmjoy release-plz would need this to be turned on to work (it needs to be enabled in organisations, and then enabled for this repository).

**Comment by jmjoy** [comment]
Is a release-pr created for every new commit? Is that too often?

**Comment by NobodyXu** [comment]
> Is a release-pr created for every new commit? Is that too often?

It's created for each push to master, if there's already an opened PR it will simply update it.

Sorry I forgot the word `push` is more precise

**Comment by NobodyXu** [comment]
> IMG_4843

@jmjoy we would need enable (it needs to be enabled in organisations first, and then enabled for this repository).

**Comment by jmjoy** [comment]
> @jmjoy we would need enable (it needs to be enabled in organisations first, and then enabled for this repository).

Enabled.

**Review by jmjoy — APPROVED** [review]

**Pull request merged**
