### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by mgrachev**

### CODE REVIEW

**Review by NobodyXu — APPROVED** [review]
Thanks!

**Comment by jmjoy** [comment]
CI is failed, upgrade MSRV?

**Comment by NobodyXu** [comment]
> CI is failed, upgrade MSRV?

We could use `cargo +nightly update -Zminimal-version`, though updating msrv is probably easier.

**Comment by jmjoy** [comment]
> We could use `cargo +nightly update -Zminimal-version`, though updating msrv is probably easier.

I agree.

**Pull request merged**
