### PR TITLE
Switch to stable cargo sparse protocol in CI.

### PR DESCRIPTION
**Pull request by jmjoy**
As rust 1.68.0 is released, Cargo's "sparse" registry protocol has been stabilized for reading the index of crates: https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol .

### CODE REVIEW

**Comment by jmjoy** [comment]
Waiting github action ubuntu image upgrade rust to 1.68.

**Comment by NobodyXu** [comment]
> Waiting github action ubuntu image upgrade rust to 1.68.

We'd better upgrade rustc manually since I don't think they will upgrade ubuntu-20.04 or even ubuntu-22.04:

     rustup toolchain install stable --minimal --no-self-upgrade

**Comment by jmjoy** [comment]
@NobodyXu I think they will, see https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#rust-tools .

**Comment by NobodyXu** [comment]
> @NobodyXu I think they will, see https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#rust-tools .

Well, I didn't know that they do that.

**Comment by jmjoy** [comment]
@NobodyXu Maybe we can upgrade the MSRV to 1.68.

**Review by NobodyXu — APPROVED** [review]

**Pull request merged**
